/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginMfaRouteImport } from './routes/login/mfa'
import { Route as LoginSelectAccountRouteImport } from './routes/login/select-account'
import { Route as AppAccountsIndexRouteImport } from './routes/_app/accounts/index'
import { Route as AppAccountsAccountIdRouteImport } from './routes/_app/accounts/$accountId'
import { Route as AppAccountsNewRouteImport } from './routes/_app/accounts/new'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products/$productId'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => LoginRouteRoute,
} as any)
const LoginSelectAccountRoute = LoginSelectAccountRouteImport.update({
  id: '/select-account',
  path: '/select-account',
  getParentRoute: () => LoginRouteRoute,
} as any)
const AppAccountsIndexRoute = AppAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsAccountIdRoute = AppAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsNewRoute = AppAccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof AppProfileRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/select-account': typeof LoginSelectAccountRoute
  '/login/': typeof LoginIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/accounts/': typeof AppAccountsIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/profile': typeof AppProfileRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/select-account': typeof LoginSelectAccountRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/accounts/new': typeof AppAccountsNewRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/accounts': typeof AppAccountsIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/_app/profile': typeof AppProfileRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/select-account': typeof LoginSelectAccountRoute
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/_app/accounts/$accountId': typeof AppAccountsAccountIdRoute
  '/_app/accounts/new': typeof AppAccountsNewRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/accounts/': typeof AppAccountsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/forgot-password'
    | '/profile'
    | '/login/mfa'
    | '/login/select-account'
    | '/login/'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/products/$productId'
    | '/products/new'
    | '/accounts/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/profile'
    | '/login/mfa'
    | '/login/select-account'
    | '/'
    | '/login'
    | '/accounts/$accountId'
    | '/accounts/new'
    | '/products/$productId'
    | '/products/new'
    | '/accounts'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/forgot-password'
    | '/_app/profile'
    | '/login/mfa'
    | '/login/select-account'
    | '/_app/'
    | '/login/'
    | '/_app/accounts/$accountId'
    | '/_app/accounts/new'
    | '/_app/products/$productId'
    | '/_app/products/new'
    | '/_app/accounts/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/login/select-account': {
      id: '/login/select-account'
      path: '/select-account'
      fullPath: '/login/select-account'
      preLoaderRoute: typeof LoginSelectAccountRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/_app/accounts/': {
      id: '/_app/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AppAccountsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounts/$accountId': {
      id: '/_app/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AppAccountsAccountIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounts/new': {
      id: '/_app/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AppAccountsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsAccountIdRoute: typeof AppAccountsAccountIdRoute
  AppAccountsNewRoute: typeof AppAccountsNewRoute
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppAccountsIndexRoute: typeof AppAccountsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAccountsAccountIdRoute: AppAccountsAccountIdRoute,
  AppAccountsNewRoute: AppAccountsNewRoute,
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppAccountsIndexRoute: AppAccountsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginMfaRoute: typeof LoginMfaRoute
  LoginSelectAccountRoute: typeof LoginSelectAccountRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginMfaRoute: LoginMfaRoute,
  LoginSelectAccountRoute: LoginSelectAccountRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
